#!/usr/bin/with-contenv bash

echo "Copying /mod-files/dns_rfc2136.py To /lsiopy/lib/python3.11/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py"
cp /mod-files/dns_rfc2136.py /lsiopy/lib/python3.11/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py
